on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y sshpass rsync

      - name: Deploy via rsync (Only Changed Files)
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete --exclude='.git' --exclude='config/database.php' --exclude='.env' -e "ssh -o StrictHostKeyChecking=no -p 65002" ./ u704283701@217.21.87.170:/home/u704283701/domains/sharat.tech/public_html/
